// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website.Data;

#nullable disable

namespace Website.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316222109_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Website.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A collection of ingredients",
                            ImageUrl = "/images/tomato.jpg",
                            Name = "My Collection"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Another collection of ingredients",
                            ImageUrl = "/images/onion.jpg",
                            Name = "Another Collection"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Yet another collection of ingredients",
                            ImageUrl = "/images/garlic.jpg",
                            Name = "Yet Another Collection"
                        });
                });

            modelBuilder.Entity("Website.Models.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainText = "This is some content."
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainText = "This is some more content."
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainText = "This is even more content."
                        });
                });

            modelBuilder.Entity("Website.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Calories")
                        .HasColumnType("REAL");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 20f,
                            Description = "Red, juicy fruit",
                            ImageUrl = "/images/tomato.jpg",
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 40f,
                            Description = "Pungent bulb",
                            ImageUrl = "/images/onion.jpg",
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 30f,
                            Description = "Strong-flavored bulb",
                            ImageUrl = "/images/garlic.jpg",
                            Name = "Garlic"
                        });
                });

            modelBuilder.Entity("Website.Models.Ingredient", b =>
                {
                    b.HasOne("Website.Models.Collection", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("CollectionId");
                });

            modelBuilder.Entity("Website.Models.Collection", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
