// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website.Data;

#nullable disable

namespace Website.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Website.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Calories")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 20f,
                            Description = "Red, juicy fruit",
                            ImageUrl = "/images/tomato.jpg",
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 40f,
                            Description = "Pungent bulb",
                            ImageUrl = "/images/onion.jpg",
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 30f,
                            Description = "Strong-flavored bulb",
                            ImageUrl = "/images/garlic.jpg",
                            Name = "Garlic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
